local Grid, gTable = ...

local myClass, classTable, classId = UnitClass("player")
local mounted = IsMounted() 

print(string.format("I, %s, am a level %d %s.", UnitName("player"), UnitLevel("player"), myClass))
for i = 1, 70 do
  local actionType, id, subType = GetActionInfo(i);
  name, rank, icon, castTime, minRange, maxRange, spellID = GetSpellInfo(id)
  if name == nil then
  else
    --print(string.format("%s is bound to %d", name, i))
  end
end

key = "ACTIONBUTTON1"
bindingAction = GetBindingByKey(key)
print(bindingAction)



--[[
local TextFrame = CreateFrame("Frame", nil, UIParent)
TextFrame:SetFrameStrata("BACKGROUND")
TextFrame:SetWidth(250) 
TextFrame:SetHeight(15) 
TextFrame.texture = TextFrame:CreateTexture(nil,"BACKGROUND")
TextFrame.texture:SetAllPoints(TextFrame)
TextFrame:SetPoint("TOPLEFT", 0, 0)
TextFrame:Show()
TextFrame.texture:SetColorTexture(0,0,0)

local fontString = TextFrame:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
fontString:SetPoint("TOPLEFT",0,0)
]]

colorZero = {0, 0, 0}                         -- Black
colorOne = {255, 255, 255}                    -- White
colorTwo= {255, 0, 0}                         -- Red
colorThree= {0, 255, 0}                       -- Green
colorFour= {0, 0, 255}                        -- Blue
colorFive = {0, 255, 255}                     -- Cyan 
colorSix = {255, 0, 255}                      -- Purple                         
colorSeven = {255, 255, 0}                    -- Yellow
colorEight = {255, 100/255, 255}              -- Light purple
colorNine = {255, 255, 100/255}               -- Soft Yellow
colorRed = {255, 0, 0}                        -- Red
colorGreen = {0, 255, 0}                      -- Green
colorBackground = {100/255, 100/255, 100/255}

-- functions

logSpam = ""
function log(msg)
    if msg ~= logSpam then
        logSpam = msg
        print(msg)
    end
end

local CELL_WIDTH = 5
local CELL_HEIGHT = 5

--[[
function CreateSquare(squareName, x, y, colour)
    local myFrame = squareName
    myFrame = CreateFrame("Frame", nil, UIParent)
    myFrame:SetFrameStrata("BACKGROUND")
    myFrame:SetWidth(CELL_WIDTH) 
    myFrame:SetHeight(CELL_HEIGHT) 
    myFrame.texture = myFrame:CreateTexture(nil,"BACKGROUND")
    myFrame.texture:SetAllPoints(myFrame)
    myFrame:SetPoint("TOPRIGHT",x,y)
    myFrame:Show()
    myFrame.texture:SetColorTexture(colour[1], colour[2], colour[3]) 
end
]]

function CreateSquare(squareName, x, y, colour)
  squareName = CreateFrame("Frame", squareName, UIParent)
  squareName:SetFrameStrata("BACKGROUND")
  squareName:SetWidth(5) 
  squareName:SetHeight(5) 
  squareName.texture = squareName:CreateTexture(nil,"BACKGROUND")
  squareName.texture:SetAllPoints(squareName)
  squareName:SetPoint("TOPRIGHT",x,y)
  squareName:Show()
  squareName.texture:SetColorTexture(colour[1], colour[2], colour[3]) 
end


CreateSquare(Signature0, 0, -90, colorZero)
CreateSquare(Signature1, 0, -95, colorOne)
CreateSquare(Signature2, 0, -100, colorTwo)
CreateSquare(Signature3, 0, -105, colorThree)
CreateSquare(Signature4, 0, -110, colorFour)
CreateSquare(Signature5, 0, -115, colorFive)
CreateSquare(Signature6, 0, -120, colorSix)
CreateSquare(Signature7, 0, -125, colorSeven)
CreateSquare(Signature8, 0, -130, colorEight)
CreateSquare(Signature9, 0, -135, colorNine)
CreateSquare(Signature10, 0, -140, colorBackground)
--CreateSquare(Map1, 0, -145, colorBackground)

-- Create Frames
Map1 = CreateFrame("Frame", nil, UIParent)
Map1:SetFrameStrata("BACKGROUND")
Map1:SetWidth(CELL_WIDTH) 
Map1:SetHeight(CELL_HEIGHT) 
Map1.texture = Map1:CreateTexture(nil,"BACKGROUND")
Map1.texture:SetAllPoints(Map1)
Map1:SetPoint("TOPRIGHT", 0, -145)
Map1:Show()
Map1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Map2 = CreateFrame("Frame", nil, UIParent)
Map2:SetFrameStrata("BACKGROUND")
Map2:SetWidth(CELL_WIDTH) 
Map2:SetHeight(CELL_HEIGHT) 
Map2.texture = Map2:CreateTexture(nil,"BACKGROUND")
Map2.texture:SetAllPoints(Map2)
Map2:SetPoint("TOPRIGHT", 0, -150)
Map2:Show()
Map2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Map3 = CreateFrame("Frame", nil, UIParent)
Map3:SetFrameStrata("BACKGROUND")
Map3:SetWidth(CELL_WIDTH) 
Map3:SetHeight(CELL_HEIGHT) 
Map3.texture = Map3:CreateTexture(nil,"BACKGROUND")
Map3.texture:SetAllPoints(Map3)
Map3:SetPoint("TOPRIGHT", 0, -155)
Map3:Show()
Map3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Map4 = CreateFrame("Frame", nil, UIParent)
Map4:SetFrameStrata("BACKGROUND")
Map4:SetWidth(CELL_WIDTH) 
Map4:SetHeight(CELL_HEIGHT) 
Map4.texture = Map4:CreateTexture(nil,"BACKGROUND")
Map4.texture:SetAllPoints(Map4)
Map4:SetPoint("TOPRIGHT", 0, -160)
Map4:Show()
Map4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Zone Frames
Zone1 = CreateFrame("Frame", nil, UIParent)
Zone1:SetFrameStrata("BACKGROUND")
Zone1:SetWidth(CELL_WIDTH) 
Zone1:SetHeight(CELL_HEIGHT) 
Zone1.texture = Zone1:CreateTexture(nil,"BACKGROUND")
Zone1.texture:SetAllPoints(Zone1)
Zone1:SetPoint("TOPRIGHT", 0, -165)
Zone1:Show()
Zone1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Zone2 = CreateFrame("Frame", nil, UIParent)
Zone2:SetFrameStrata("BACKGROUND")
Zone2:SetWidth(CELL_WIDTH) 
Zone2:SetHeight(CELL_HEIGHT) 
Zone2.texture = Zone2:CreateTexture(nil,"BACKGROUND")
Zone2.texture:SetAllPoints(Zone2)
Zone2:SetPoint("TOPRIGHT", 0, -170)
Zone2:Show()
Zone2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Zone3 = CreateFrame("Frame", nil, UIParent)
Zone3:SetFrameStrata("BACKGROUND")
Zone3:SetWidth(CELL_WIDTH) 
Zone3:SetHeight(CELL_HEIGHT) 
Zone3.texture = Zone3:CreateTexture(nil,"BACKGROUND")
Zone3.texture:SetAllPoints(Zone3)
Zone3:SetPoint("TOPRIGHT", 0, -175)
Zone3:Show()
Zone3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Zone4 = CreateFrame("Frame", nil, UIParent)
Zone4:SetFrameStrata("BACKGROUND")
Zone4:SetWidth(CELL_WIDTH) 
Zone4:SetHeight(CELL_HEIGHT) 
Zone4.texture = Zone4:CreateTexture(nil,"BACKGROUND")
Zone4.texture:SetAllPoints(Zone4)
Zone4:SetPoint("TOPRIGHT", 0, -180)
Zone4:Show()
Zone4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- X Frames
XFrame1 = CreateFrame("Frame", nil, UIParent)
XFrame1:SetFrameStrata("BACKGROUND")
XFrame1:SetWidth(CELL_WIDTH) 
XFrame1:SetHeight(CELL_HEIGHT) 
XFrame1.texture = XFrame1:CreateTexture(nil,"BACKGROUND")
XFrame1.texture:SetAllPoints(XFrame1)
XFrame1:SetPoint("TOPRIGHT", 0, -185)
XFrame1:Show()
XFrame1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

XFrame2 = CreateFrame("Frame", nil, UIParent)
XFrame2:SetFrameStrata("BACKGROUND")
XFrame2:SetWidth(CELL_WIDTH) 
XFrame2:SetHeight(CELL_HEIGHT) 
XFrame2.texture = XFrame2:CreateTexture(nil,"BACKGROUND")
XFrame2.texture:SetAllPoints(XFrame2)
XFrame2:SetPoint("TOPRIGHT", 0, -190)
XFrame2:Show()
XFrame2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

XFrame3 = CreateFrame("Frame", nil, UIParent)
XFrame3:SetFrameStrata("BACKGROUND")
XFrame3:SetWidth(CELL_WIDTH) 
XFrame3:SetHeight(CELL_HEIGHT) 
XFrame3.texture = XFrame3:CreateTexture(nil,"BACKGROUND")
XFrame3.texture:SetAllPoints(XFrame3)
XFrame3:SetPoint("TOPRIGHT", 0, -195)
XFrame3:Show()
XFrame3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

XFrame4 = CreateFrame("Frame", nil, UIParent)
XFrame4:SetFrameStrata("BACKGROUND")
XFrame4:SetWidth(CELL_WIDTH) 
XFrame4:SetHeight(CELL_HEIGHT) 
XFrame4.texture = XFrame4:CreateTexture(nil,"BACKGROUND")
XFrame4.texture:SetAllPoints(XFrame4)
XFrame4:SetPoint("TOPRIGHT", 0, -200)
XFrame4:Show()
XFrame4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Y Frames
YFrame1 = CreateFrame("Frame", nil, UIParent)
YFrame1:SetFrameStrata("BACKGROUND")
YFrame1:SetWidth(CELL_WIDTH) 
YFrame1:SetHeight(CELL_HEIGHT) 
YFrame1.texture = YFrame1:CreateTexture(nil,"BACKGROUND")
YFrame1.texture:SetAllPoints(YFrame1)
YFrame1:SetPoint("TOPRIGHT", 0, -205)
YFrame1:Show()
YFrame1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

YFrame2 = CreateFrame("Frame", nil, UIParent)
YFrame2:SetFrameStrata("BACKGROUND")
YFrame2:SetWidth(CELL_WIDTH) 
YFrame2:SetHeight(CELL_HEIGHT) 
YFrame2.texture = YFrame2:CreateTexture(nil,"BACKGROUND")
YFrame2.texture:SetAllPoints(YFrame2)
YFrame2:SetPoint("TOPRIGHT", 0, -210)
YFrame2:Show()
YFrame2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

YFrame3 = CreateFrame("Frame", nil, UIParent)
YFrame3:SetFrameStrata("BACKGROUND")
YFrame3:SetWidth(CELL_WIDTH) 
YFrame3:SetHeight(CELL_HEIGHT) 
YFrame3.texture = YFrame3:CreateTexture(nil,"BACKGROUND")
YFrame3.texture:SetAllPoints(YFrame3)
YFrame3:SetPoint("TOPRIGHT", 0, -215)
YFrame3:Show()
YFrame3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

YFrame4 = CreateFrame("Frame", nil, UIParent)
YFrame4:SetFrameStrata("BACKGROUND")
YFrame4:SetWidth(CELL_WIDTH) 
YFrame4:SetHeight(CELL_HEIGHT) 
YFrame4.texture = YFrame4:CreateTexture(nil,"BACKGROUND")
YFrame4.texture:SetAllPoints(YFrame4)
YFrame4:SetPoint("TOPRIGHT", 0, -220)
YFrame4:Show()
YFrame4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Facing Frames
Facing1 = CreateFrame("Frame", nil, UIParent)
Facing1:SetFrameStrata("BACKGROUND")
Facing1:SetWidth(CELL_WIDTH) 
Facing1:SetHeight(CELL_HEIGHT) 
Facing1.texture = Facing1:CreateTexture(nil,"BACKGROUND")
Facing1.texture:SetAllPoints(Facing1)
Facing1:SetPoint("TOPRIGHT", 0, -225)
Facing1:Show()
Facing1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Facing2 = CreateFrame("Frame", nil, UIParent)
Facing2:SetFrameStrata("BACKGROUND")
Facing2:SetWidth(CELL_WIDTH) 
Facing2:SetHeight(CELL_HEIGHT) 
Facing2.texture = Facing2:CreateTexture(nil,"BACKGROUND")
Facing2.texture:SetAllPoints(Facing2)
Facing2:SetPoint("TOPRIGHT", 0, -230)
Facing2:Show()
Facing2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Facing3 = CreateFrame("Frame", nil, UIParent)
Facing3:SetFrameStrata("BACKGROUND")
Facing3:SetWidth(CELL_WIDTH) 
Facing3:SetHeight(CELL_HEIGHT) 
Facing3.texture = Facing3:CreateTexture(nil,"BACKGROUND")
Facing3.texture:SetAllPoints(Facing3)
Facing3:SetPoint("TOPRIGHT", 0, -235)
Facing3:Show()
Facing3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Facing4 = CreateFrame("Frame", nil, UIParent)
Facing4:SetFrameStrata("BACKGROUND")
Facing4:SetWidth(CELL_WIDTH) 
Facing4:SetHeight(CELL_HEIGHT) 
Facing4.texture = Facing4:CreateTexture(nil,"BACKGROUND")
Facing4.texture:SetAllPoints(Facing4)
Facing4:SetPoint("TOPRIGHT", 0, -240)
Facing4:Show()
Facing4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Corpse X Frames
CorpseX1 = CreateFrame("Frame", nil, UIParent)
CorpseX1:SetFrameStrata("BACKGROUND")
CorpseX1:SetWidth(CELL_WIDTH) 
CorpseX1:SetHeight(CELL_HEIGHT) 
CorpseX1.texture = CorpseX1:CreateTexture(nil,"BACKGROUND")
CorpseX1.texture:SetAllPoints(CorpseX1)
CorpseX1:SetPoint("TOPRIGHT", 0, -245)
CorpseX1:Show()
CorpseX1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseX2 = CreateFrame("Frame", nil, UIParent)
CorpseX2:SetFrameStrata("BACKGROUND")
CorpseX2:SetWidth(CELL_WIDTH) 
CorpseX2:SetHeight(CELL_HEIGHT) 
CorpseX2.texture = CorpseX2:CreateTexture(nil,"BACKGROUND")
CorpseX2.texture:SetAllPoints(CorpseX2)
CorpseX2:SetPoint("TOPRIGHT", 0, -250)
CorpseX2:Show()
CorpseX2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseX3 = CreateFrame("Frame", nil, UIParent)
CorpseX3:SetFrameStrata("BACKGROUND")
CorpseX3:SetWidth(CELL_WIDTH) 
CorpseX3:SetHeight(CELL_HEIGHT) 
CorpseX3.texture = CorpseX3:CreateTexture(nil,"BACKGROUND")
CorpseX3.texture:SetAllPoints(CorpseX3)
CorpseX3:SetPoint("TOPRIGHT", 0, -255)
CorpseX3:Show()
CorpseX3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseX4 = CreateFrame("Frame", nil, UIParent)
CorpseX4:SetFrameStrata("BACKGROUND")
CorpseX4:SetWidth(CELL_WIDTH) 
CorpseX4:SetHeight(CELL_HEIGHT) 
CorpseX4.texture = CorpseX4:CreateTexture(nil,"BACKGROUND")
CorpseX4.texture:SetAllPoints(CorpseX4)
CorpseX4:SetPoint("TOPRIGHT", 0, -260)
CorpseX4:Show()
CorpseX4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Corpse Y Frames
CorpseY1 = CreateFrame("Frame", nil, UIParent)
CorpseY1:SetFrameStrata("BACKGROUND")
CorpseY1:SetWidth(CELL_WIDTH) 
CorpseY1:SetHeight(CELL_HEIGHT) 
CorpseY1.texture = CorpseY1:CreateTexture(nil,"BACKGROUND")
CorpseY1.texture:SetAllPoints(CorpseY1)
CorpseY1:SetPoint("TOPRIGHT", 0, -265)
CorpseY1:Show()
CorpseY1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseY2 = CreateFrame("Frame", nil, UIParent)
CorpseY2:SetFrameStrata("BACKGROUND")
CorpseY2:SetWidth(CELL_WIDTH) 
CorpseY2:SetHeight(CELL_HEIGHT) 
CorpseY2.texture = CorpseY2:CreateTexture(nil,"BACKGROUND")
CorpseY2.texture:SetAllPoints(CorpseY2)
CorpseY2:SetPoint("TOPRIGHT", 0, -270)
CorpseY2:Show()
CorpseY2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseY3 = CreateFrame("Frame", nil, UIParent)
CorpseY3:SetFrameStrata("BACKGROUND")
CorpseY3:SetWidth(CELL_WIDTH) 
CorpseY3:SetHeight(CELL_HEIGHT) 
CorpseY3.texture = CorpseY3:CreateTexture(nil,"BACKGROUND")
CorpseY3.texture:SetAllPoints(CorpseY3)
CorpseY3:SetPoint("TOPRIGHT", 0, -275)
CorpseY3:Show()
CorpseY3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CorpseY4 = CreateFrame("Frame", nil, UIParent)
CorpseY4:SetFrameStrata("BACKGROUND")
CorpseY4:SetWidth(CELL_WIDTH) 
CorpseY4:SetHeight(CELL_HEIGHT) 
CorpseY4.texture = CorpseY4:CreateTexture(nil,"BACKGROUND")
CorpseY4.texture:SetAllPoints(CorpseY4)
CorpseY4:SetPoint("TOPRIGHT", 0, -280)
CorpseY4:Show()
CorpseY4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Command Frames
CommandKill = CreateFrame("Frame", nil, UIParent)
CommandKill:SetFrameStrata("BACKGROUND")
CommandKill:SetWidth(CELL_WIDTH) 
CommandKill:SetHeight(CELL_HEIGHT) 
CommandKill.texture = CommandKill:CreateTexture(nil,"BACKGROUND")
CommandKill.texture:SetAllPoints(CommandKill)
CommandKill:SetPoint("TOPRIGHT", 0, -285)
CommandKill:Show()
CommandKill.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CommandStartStop = CreateFrame("Frame", nil, UIParent)
CommandStartStop:SetFrameStrata("BACKGROUND")
CommandStartStop:SetWidth(CELL_WIDTH) 
CommandStartStop:SetHeight(CELL_HEIGHT) 
CommandStartStop.texture = CommandStartStop:CreateTexture(nil,"BACKGROUND")
CommandStartStop.texture:SetAllPoints(CommandStartStop)
CommandStartStop:SetPoint("TOPRIGHT", 0, -290)
CommandStartStop:Show()
CommandStartStop.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CommandRecordPath = CreateFrame("Frame", nil, UIParent)
CommandRecordPath:SetFrameStrata("BACKGROUND")
CommandRecordPath:SetWidth(CELL_WIDTH) 
CommandRecordPath:SetHeight(CELL_HEIGHT) 
CommandRecordPath.texture = CommandRecordPath:CreateTexture(nil,"BACKGROUND")
CommandRecordPath.texture:SetAllPoints(CommandRecordPath)
CommandRecordPath:SetPoint("TOPRIGHT", 0, -295)
CommandRecordPath:Show()
CommandRecordPath.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

UnitCanAttackFrame = CreateFrame("Frame", nil, UIParent)
UnitCanAttackFrame:SetFrameStrata("BACKGROUND")
UnitCanAttackFrame:SetWidth(CELL_WIDTH) 
UnitCanAttackFrame:SetHeight(CELL_HEIGHT) 
UnitCanAttackFrame.texture = UnitCanAttackFrame:CreateTexture(nil,"BACKGROUND")
UnitCanAttackFrame.texture:SetAllPoints(UnitCanAttackFrame)
UnitCanAttackFrame:SetPoint("TOPRIGHT", 0, -300)
UnitCanAttackFrame:Show()
UnitCanAttackFrame.texture:SetColorTexture(colorBackground[1], colorBackground[2], colorBackground[3])

-- NpcIds
NpcId1 = CreateFrame("Frame", nil, UIParent)
NpcId1:SetFrameStrata("BACKGROUND")
NpcId1:SetWidth(CELL_WIDTH) 
NpcId1:SetHeight(CELL_HEIGHT) 
NpcId1.texture = NpcId1:CreateTexture(nil,"BACKGROUND")
NpcId1.texture:SetAllPoints(NpcId1)
NpcId1:SetPoint("TOPRIGHT", 0, -305)
NpcId1:Show()
NpcId1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

NpcId2 = CreateFrame("Frame", nil, UIParent)
NpcId2:SetFrameStrata("BACKGROUND")
NpcId2:SetWidth(CELL_WIDTH) 
NpcId2:SetHeight(CELL_HEIGHT) 
NpcId2.texture = NpcId2:CreateTexture(nil,"BACKGROUND")
NpcId2.texture:SetAllPoints(NpcId2)
NpcId2:SetPoint("TOPRIGHT", 0, -310)
NpcId2:Show()
NpcId2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

NpcId3 = CreateFrame("Frame", nil, UIParent)
NpcId3:SetFrameStrata("BACKGROUND")
NpcId3:SetWidth(CELL_WIDTH) 
NpcId3:SetHeight(CELL_HEIGHT) 
NpcId3.texture = NpcId3:CreateTexture(nil,"BACKGROUND")
NpcId3.texture:SetAllPoints(NpcId3)
NpcId3:SetPoint("TOPRIGHT", 0, -315)
NpcId3:Show()
NpcId3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

NpcId4 = CreateFrame("Frame", nil, UIParent)
NpcId4:SetFrameStrata("BACKGROUND")
NpcId4:SetWidth(CELL_WIDTH) 
NpcId4:SetHeight(CELL_HEIGHT) 
NpcId4.texture = NpcId4:CreateTexture(nil,"BACKGROUND")
NpcId4.texture:SetAllPoints(NpcId4)
NpcId4:SetPoint("TOPRIGHT", 0, -320)
NpcId4:Show()
NpcId4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

NpcId5 = CreateFrame("Frame", nil, UIParent)
NpcId5:SetFrameStrata("BACKGROUND")
NpcId5:SetWidth(CELL_WIDTH) 
NpcId5:SetHeight(CELL_HEIGHT) 
NpcId5.texture = NpcId5:CreateTexture(nil,"BACKGROUND")
NpcId5.texture:SetAllPoints(NpcId5)
NpcId5:SetPoint("TOPRIGHT", 0, -325)
NpcId5:Show()
NpcId5.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

NpcId6 = CreateFrame("Frame", nil, UIParent)
NpcId6:SetFrameStrata("BACKGROUND")
NpcId6:SetWidth(CELL_WIDTH) 
NpcId6:SetHeight(CELL_HEIGHT) 
NpcId6.texture = NpcId6:CreateTexture(nil,"BACKGROUND")
NpcId6.texture:SetAllPoints(NpcId6)
NpcId6:SetPoint("TOPRIGHT", 0, -330)
NpcId6:Show()
NpcId6.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Guid1 = CreateFrame("Frame", nil, UIParent)
Guid1:SetFrameStrata("BACKGROUND")
Guid1:SetWidth(CELL_WIDTH) 
Guid1:SetHeight(CELL_HEIGHT) 
Guid1.texture = Guid1:CreateTexture(nil,"BACKGROUND")
Guid1.texture:SetAllPoints(Guid1)
Guid1:SetPoint("TOPRIGHT", 0, -335)
Guid1:Show()
Guid1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Guid2 = CreateFrame("Frame", nil, UIParent)
Guid2:SetFrameStrata("BACKGROUND")
Guid2:SetWidth(CELL_WIDTH) 
Guid2:SetHeight(CELL_HEIGHT) 
Guid2.texture = Guid2:CreateTexture(nil,"BACKGROUND")
Guid2.texture:SetAllPoints(Guid2)
Guid2:SetPoint("TOPRIGHT", 0, -340)
Guid2:Show()
Guid2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Guid3 = CreateFrame("Frame", nil, UIParent)
Guid3:SetFrameStrata("BACKGROUND")
Guid3:SetWidth(CELL_WIDTH) 
Guid3:SetHeight(CELL_HEIGHT) 
Guid3.texture = Guid3:CreateTexture(nil,"BACKGROUND")
Guid3.texture:SetAllPoints(Guid3)
Guid3:SetPoint("TOPRIGHT", 0, -345)
Guid3:Show()
Guid3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

Guid4 = CreateFrame("Frame", nil, UIParent)
Guid4:SetFrameStrata("BACKGROUND")
Guid4:SetWidth(CELL_WIDTH) 
Guid4:SetHeight(CELL_HEIGHT) 
Guid4.texture = Guid4:CreateTexture(nil,"BACKGROUND")
Guid4.texture:SetAllPoints(Guid4)
Guid4:SetPoint("TOPRIGHT", 0, -350)
Guid4:Show()
Guid4.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Quest 1 Frames
QuestGrid11 = CreateFrame("Frame", nil, UIParent)
QuestGrid11:SetFrameStrata("BACKGROUND")
QuestGrid11:SetWidth(CELL_WIDTH) 
QuestGrid11:SetHeight(CELL_HEIGHT) 
QuestGrid11.texture = QuestGrid11:CreateTexture(nil,"BACKGROUND")
QuestGrid11.texture:SetAllPoints(QuestGrid11)
QuestGrid11:SetPoint("TOPRIGHT", 0, -355)
QuestGrid11:Show()
QuestGrid11.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid12 = CreateFrame("Frame", nil, UIParent)
QuestGrid12:SetFrameStrata("BACKGROUND")
QuestGrid12:SetWidth(CELL_WIDTH) 
QuestGrid12:SetHeight(CELL_HEIGHT) 
QuestGrid12.texture = QuestGrid12:CreateTexture(nil,"BACKGROUND")
QuestGrid12.texture:SetAllPoints(QuestGrid12)
QuestGrid12:SetPoint("TOPRIGHT", 0, -360)
QuestGrid12:Show()
QuestGrid12.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid13 = CreateFrame("Frame", nil, UIParent)
QuestGrid13:SetFrameStrata("BACKGROUND")
QuestGrid13:SetWidth(CELL_WIDTH) 
QuestGrid13:SetHeight(CELL_HEIGHT) 
QuestGrid13.texture = QuestGrid13:CreateTexture(nil,"BACKGROUND")
QuestGrid13.texture:SetAllPoints(QuestGrid13)
QuestGrid13:SetPoint("TOPRIGHT", 0, -365)
QuestGrid13:Show()
QuestGrid13.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid14 = CreateFrame("Frame", nil, UIParent)
QuestGrid14:SetFrameStrata("BACKGROUND")
QuestGrid14:SetWidth(CELL_WIDTH) 
QuestGrid14:SetHeight(CELL_HEIGHT) 
QuestGrid14.texture = QuestGrid14:CreateTexture(nil,"BACKGROUND")
QuestGrid14.texture:SetAllPoints(QuestGrid14)
QuestGrid14:SetPoint("TOPRIGHT", 0, -370)
QuestGrid14:Show()
QuestGrid14.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid15 = CreateFrame("Frame", nil, UIParent)
QuestGrid15:SetFrameStrata("BACKGROUND")
QuestGrid15:SetWidth(CELL_WIDTH) 
QuestGrid15:SetHeight(CELL_HEIGHT) 
QuestGrid15.texture = QuestGrid15:CreateTexture(nil,"BACKGROUND")
QuestGrid15.texture:SetAllPoints(QuestGrid15)
QuestGrid15:SetPoint("TOPRIGHT", 0, -375)
QuestGrid15:Show()
QuestGrid15.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Quest 2 Frames
QuestGrid21 = CreateFrame("Frame", nil, UIParent)
QuestGrid21:SetFrameStrata("BACKGROUND")
QuestGrid21:SetWidth(CELL_WIDTH) 
QuestGrid21:SetHeight(CELL_HEIGHT) 
QuestGrid21.texture = QuestGrid21:CreateTexture(nil,"BACKGROUND")
QuestGrid21.texture:SetAllPoints(QuestGrid21)
QuestGrid21:SetPoint("TOPRIGHT", 0, -380)
QuestGrid21:Show()
QuestGrid21.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid22 = CreateFrame("Frame", nil, UIParent)
QuestGrid22:SetFrameStrata("BACKGROUND")
QuestGrid22:SetWidth(CELL_WIDTH) 
QuestGrid22:SetHeight(CELL_HEIGHT) 
QuestGrid22.texture = QuestGrid22:CreateTexture(nil,"BACKGROUND")
QuestGrid22.texture:SetAllPoints(QuestGrid22)
QuestGrid22:SetPoint("TOPRIGHT", 0, -385)
QuestGrid22:Show()
QuestGrid22.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid23 = CreateFrame("Frame", nil, UIParent)
QuestGrid23:SetFrameStrata("BACKGROUND")
QuestGrid23:SetWidth(CELL_WIDTH) 
QuestGrid23:SetHeight(CELL_HEIGHT) 
QuestGrid23.texture = QuestGrid23:CreateTexture(nil,"BACKGROUND")
QuestGrid23.texture:SetAllPoints(QuestGrid23)
QuestGrid23:SetPoint("TOPRIGHT", 0, -390)
QuestGrid23:Show()
QuestGrid23.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid24 = CreateFrame("Frame", nil, UIParent)
QuestGrid24:SetFrameStrata("BACKGROUND")
QuestGrid24:SetWidth(CELL_WIDTH) 
QuestGrid24:SetHeight(CELL_HEIGHT) 
QuestGrid24.texture = QuestGrid24:CreateTexture(nil,"BACKGROUND")
QuestGrid24.texture:SetAllPoints(QuestGrid24)
QuestGrid24:SetPoint("TOPRIGHT", 0, -395)
QuestGrid24:Show()
QuestGrid24.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid25 = CreateFrame("Frame", nil, UIParent)
QuestGrid25:SetFrameStrata("BACKGROUND")
QuestGrid25:SetWidth(CELL_WIDTH) 
QuestGrid25:SetHeight(CELL_HEIGHT) 
QuestGrid25.texture = QuestGrid25:CreateTexture(nil,"BACKGROUND")
QuestGrid25.texture:SetAllPoints(QuestGrid25)
QuestGrid25:SetPoint("TOPRIGHT", 0, -400)
QuestGrid25:Show()
QuestGrid25.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Quest 3 Frames
QuestGrid31 = CreateFrame("Frame", nil, UIParent)
QuestGrid31:SetFrameStrata("BACKGROUND")
QuestGrid31:SetWidth(CELL_WIDTH) 
QuestGrid31:SetHeight(CELL_HEIGHT) 
QuestGrid31.texture = QuestGrid31:CreateTexture(nil,"BACKGROUND")
QuestGrid31.texture:SetAllPoints(QuestGrid31)
QuestGrid31:SetPoint("TOPRIGHT", 0, -405)
QuestGrid31:Show()
QuestGrid31.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid32 = CreateFrame("Frame", nil, UIParent)
QuestGrid32:SetFrameStrata("BACKGROUND")
QuestGrid32:SetWidth(CELL_WIDTH) 
QuestGrid32:SetHeight(CELL_HEIGHT) 
QuestGrid32.texture = QuestGrid32:CreateTexture(nil,"BACKGROUND")
QuestGrid32.texture:SetAllPoints(QuestGrid32)
QuestGrid32:SetPoint("TOPRIGHT", 0, -410)
QuestGrid32:Show()
QuestGrid32.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid33 = CreateFrame("Frame", nil, UIParent)
QuestGrid33:SetFrameStrata("BACKGROUND")
QuestGrid33:SetWidth(CELL_WIDTH) 
QuestGrid33:SetHeight(CELL_HEIGHT) 
QuestGrid33.texture = QuestGrid33:CreateTexture(nil,"BACKGROUND")
QuestGrid33.texture:SetAllPoints(QuestGrid33)
QuestGrid33:SetPoint("TOPRIGHT", 0, -415)
QuestGrid33:Show()
QuestGrid33.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid34 = CreateFrame("Frame", nil, UIParent)
QuestGrid34:SetFrameStrata("BACKGROUND")
QuestGrid34:SetWidth(CELL_WIDTH) 
QuestGrid34:SetHeight(CELL_HEIGHT) 
QuestGrid34.texture = QuestGrid34:CreateTexture(nil,"BACKGROUND")
QuestGrid34.texture:SetAllPoints(QuestGrid34)
QuestGrid34:SetPoint("TOPRIGHT", 0, -420)
QuestGrid34:Show()
QuestGrid34.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid35 = CreateFrame("Frame", nil, UIParent)
QuestGrid35:SetFrameStrata("BACKGROUND")
QuestGrid35:SetWidth(CELL_WIDTH) 
QuestGrid35:SetHeight(CELL_HEIGHT) 
QuestGrid35.texture = QuestGrid35:CreateTexture(nil,"BACKGROUND")
QuestGrid35.texture:SetAllPoints(QuestGrid35)
QuestGrid35:SetPoint("TOPRIGHT", 0, -425)
QuestGrid35:Show()
QuestGrid35.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- Quest 4 Frames
QuestGrid41 = CreateFrame("Frame", nil, UIParent)
QuestGrid41:SetFrameStrata("BACKGROUND")
QuestGrid41:SetWidth(CELL_WIDTH) 
QuestGrid41:SetHeight(CELL_HEIGHT) 
QuestGrid41.texture = QuestGrid41:CreateTexture(nil,"BACKGROUND")
QuestGrid41.texture:SetAllPoints(QuestGrid41)
QuestGrid41:SetPoint("TOPRIGHT", 0, -430)
QuestGrid41:Show()
QuestGrid41.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid42 = CreateFrame("Frame", nil, UIParent)
QuestGrid42:SetFrameStrata("BACKGROUND")
QuestGrid42:SetWidth(CELL_WIDTH) 
QuestGrid42:SetHeight(CELL_HEIGHT) 
QuestGrid42.texture = QuestGrid42:CreateTexture(nil,"BACKGROUND")
QuestGrid42.texture:SetAllPoints(QuestGrid42)
QuestGrid42:SetPoint("TOPRIGHT", 0, -435)
QuestGrid42:Show()
QuestGrid42.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid43 = CreateFrame("Frame", nil, UIParent)
QuestGrid43:SetFrameStrata("BACKGROUND")
QuestGrid43:SetWidth(CELL_WIDTH) 
QuestGrid43:SetHeight(CELL_HEIGHT) 
QuestGrid43.texture = QuestGrid43:CreateTexture(nil,"BACKGROUND")
QuestGrid43.texture:SetAllPoints(QuestGrid43)
QuestGrid43:SetPoint("TOPRIGHT", 0, -440)
QuestGrid43:Show()
QuestGrid43.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid44 = CreateFrame("Frame", nil, UIParent)
QuestGrid44:SetFrameStrata("BACKGROUND")
QuestGrid44:SetWidth(CELL_WIDTH) 
QuestGrid44:SetHeight(CELL_HEIGHT) 
QuestGrid44.texture = QuestGrid44:CreateTexture(nil,"BACKGROUND")
QuestGrid44.texture:SetAllPoints(QuestGrid44)
QuestGrid44:SetPoint("TOPRIGHT", 0, -445)
QuestGrid44:Show()
QuestGrid44.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

QuestGrid45 = CreateFrame("Frame", nil, UIParent)
QuestGrid45:SetFrameStrata("BACKGROUND")
QuestGrid45:SetWidth(CELL_WIDTH) 
QuestGrid45:SetHeight(CELL_HEIGHT) 
QuestGrid45.texture = QuestGrid45:CreateTexture(nil,"BACKGROUND")
QuestGrid45.texture:SetAllPoints(QuestGrid45)
QuestGrid45:SetPoint("TOPRIGHT", 0, -450)
QuestGrid45:Show()
QuestGrid45.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- am I in combat?
InCombatFrame = CreateFrame("Frame", nil, UIParent)
InCombatFrame:SetFrameStrata("BACKGROUND")
InCombatFrame:SetWidth(CELL_WIDTH) 
InCombatFrame:SetHeight(CELL_HEIGHT) 
InCombatFrame.texture = InCombatFrame:CreateTexture(nil,"BACKGROUND")
InCombatFrame.texture:SetAllPoints(InCombatFrame)
InCombatFrame:SetPoint("TOPRIGHT", 0, -455)
InCombatFrame:Show()
InCombatFrame.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- My level
LevelFrame1 = CreateFrame("Frame", nil, UIParent)
LevelFrame1:SetFrameStrata("BACKGROUND")
LevelFrame1:SetWidth(CELL_WIDTH) 
LevelFrame1:SetHeight(CELL_HEIGHT) 
LevelFrame1.texture = LevelFrame1:CreateTexture(nil,"BACKGROUND")
LevelFrame1.texture:SetAllPoints(LevelFrame1)
LevelFrame1:SetPoint("TOPRIGHT", 0, -460)
LevelFrame1:Show()
LevelFrame1.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

LevelFrame2 = CreateFrame("Frame", nil, UIParent)
LevelFrame2:SetFrameStrata("BACKGROUND")
LevelFrame2:SetWidth(CELL_WIDTH) 
LevelFrame2:SetHeight(CELL_HEIGHT) 
LevelFrame2.texture = LevelFrame2:CreateTexture(nil,"BACKGROUND")
LevelFrame2.texture:SetAllPoints(LevelFrame2)
LevelFrame2:SetPoint("TOPRIGHT", 0, -465)
LevelFrame2:Show()
LevelFrame2.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

LevelFrame3 = CreateFrame("Frame", nil, UIParent)
LevelFrame3:SetFrameStrata("BACKGROUND")
LevelFrame3:SetWidth(CELL_WIDTH) 
LevelFrame3:SetHeight(CELL_HEIGHT) 
LevelFrame3.texture = LevelFrame3:CreateTexture(nil,"BACKGROUND")
LevelFrame3.texture:SetAllPoints(LevelFrame3)
LevelFrame3:SetPoint("TOPRIGHT", 0, -470)
LevelFrame3:Show()
LevelFrame3.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

CommandKeyToPress0 = CreateFrame("Frame", nil, UIParent)
CommandKeyToPress0:SetFrameStrata("BACKGROUND")
CommandKeyToPress0:SetWidth(CELL_WIDTH) 
CommandKeyToPress0:SetHeight(CELL_HEIGHT) 
CommandKeyToPress0.texture = CommandKeyToPress0:CreateTexture(nil,"BACKGROUND")
CommandKeyToPress0.texture:SetAllPoints(CommandKeyToPress0)
CommandKeyToPress0:SetPoint("TOPRIGHT", 0, -475)
CommandKeyToPress0:Show()
CommandKeyToPress0.texture:SetColorTexture(colorBackground[1], colorBackground[2], colorBackground[3])

CommandKeyToPress1 = CreateFrame("Frame", nil, UIParent)
CommandKeyToPress1:SetFrameStrata("BACKGROUND")
CommandKeyToPress1:SetWidth(CELL_WIDTH) 
CommandKeyToPress1:SetHeight(CELL_HEIGHT) 
CommandKeyToPress1.texture = CommandKeyToPress1:CreateTexture(nil,"BACKGROUND")
CommandKeyToPress1.texture:SetAllPoints(CommandKeyToPress1)
CommandKeyToPress1:SetPoint("TOPRIGHT", 0, -480)
CommandKeyToPress1:Show()
CommandKeyToPress1.texture:SetColorTexture(colorBackground[1], colorBackground[2], colorBackground[3])

CommandInteractNeeded = CreateFrame("Frame", nil, UIParent)
CommandInteractNeeded:SetFrameStrata("BACKGROUND")
CommandInteractNeeded:SetWidth(CELL_WIDTH)
CommandInteractNeeded:SetHeight(CELL_HEIGHT) 
CommandInteractNeeded.texture = CommandInteractNeeded:CreateTexture(nil,"BACKGROUND")
CommandInteractNeeded.texture:SetAllPoints(CommandInteractNeeded)
CommandInteractNeeded:SetPoint("TOPRIGHT", 0, -485)
CommandInteractNeeded:Show()
CommandInteractNeeded.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])

-- buttons
local BtnStopGo = CreateFrame("Button", nil, UIParent, "UIPanelButtonTemplate")
BtnStopGo:SetSize(100,20)
BtnStopGo:SetPoint("RIGHT", mainframe, "RIGHT", -20, -275)
BtnStopGo:RegisterForClicks("AnyUp")
BtnStopGo:SetText("Stop Now")
BtnStopGo:SetScript("OnClick", function(self,btn)
      if self:GetText()=="Stop Now" then
        CommandStartStop.texture:SetColorTexture(255,255,255)        
         self:SetText("Start")
      else
            CommandStartStop.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])
         self:SetText("Stop Now")
      end
end)
BtnStopGo:SetMovable(true)
BtnStopGo:RegisterForDrag("LeftBtnStopGo")
BtnStopGo:SetScript("OnDragStart", BtnStopGo.StartMoving)
BtnStopGo:SetScript("OnDragStop", BtnStopGo.StopMovingOrSizing)
BtnStopGo:SetScript("OnHide", BtnStopGo.StopMovingOrSizing)
BtnStopGo:Show()


local BtnRecord = CreateFrame("Button", nil, UIParent, "UIPanelButtonTemplate")
BtnRecord:SetSize(100,20)
BtnRecord:SetPoint("RIGHT", mainframe, "RIGHT", -120, -275)
BtnRecord:RegisterForClicks("AnyUp")
BtnRecord:SetText("Record")
BtnRecord:SetScript("OnClick", function(self,btn)
      if self:GetText()=="Record" then
        CommandRecordPath.texture:SetColorTexture(255,255,255)        
         self:SetText("Stop Recording")
      else
            CommandRecordPath.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])
         self:SetText("Record")
      end
end)
BtnRecord:SetMovable(true)
BtnRecord:RegisterForDrag("LeftBtnRecord")
BtnRecord:SetScript("OnDragStart", BtnRecord.StartMoving)
BtnRecord:SetScript("OnDragStop", BtnRecord.StopMovingOrSizing)
BtnRecord:SetScript("OnHide", BtnRecord.StopMovingOrSizing)
BtnRecord:Show()

BtnKill = CreateFrame("Button", nil, UIParent, "UIPanelButtonTemplate")
BtnKill:SetSize(100,20)
BtnKill:SetPoint("RIGHT", mainframe, "RIGHT", -220, -275)
BtnKill:RegisterForClicks("AnyUp")
BtnKill:SetText("Kill")
BtnKill:SetScript("OnClick", function(self,btn)
      if self:GetText()=="Kill" then
        CommandKill.texture:SetColorTexture(255,255,255)        
        self:SetText("Stop Fighting")
      else
        CommandKill.texture:SetColorTexture(colorZero[1], colorZero[2], colorZero[3])
        self:SetText("Kill")
      end
end)
BtnKill:SetMovable(true)
BtnKill:RegisterForDrag("LeftBtnKill")
BtnKill:SetScript("OnDragStart", BtnKill.StartMoving)
BtnKill:SetScript("OnDragStop", BtnKill.StopMovingOrSizing)
BtnKill:SetScript("OnHide", BtnKill.StopMovingOrSizing)
BtnKill:Show()

-- The work is done here
EventFrame = CreateFrame("Frame") 
EventFrame:SetScript("OnEvent", EventFrame.OnEvent)
EventFrame:RegisterEvent("MERCHANT_SHOW")
EventFrame:RegisterEvent("PLAYER_LOGIN")
EventFrame:RegisterEvent("QUEST_GREETING")
EventFrame:RegisterEvent("QUEST_DETAIL")
EventFrame:RegisterEvent("QUEST_ACCEPT_CONFIRM")
EventFrame:RegisterEvent("QUEST_ACCEPTED")
EventFrame:RegisterEvent("QUEST_PROGRESS")
EventFrame:RegisterEvent("QUEST_ITEM_UPDATE")
EventFrame:RegisterEvent("QUEST_COMPLETE")
EventFrame:RegisterEvent("QUEST_FINISHED")
EventFrame:RegisterEvent("QUEST_AUTOCOMPLETE")

function EventFrame:OnUpdate()
    
    UpdateGrid()    
    gTable.CastSpells()
    --fontString:SetText(message)
    --log(message)
    
   
end


EventFrame:SetScript("OnUpdate", EventFrame.OnUpdate)

EventFrame:SetScript("OnEvent", function(self,event, ...)
    if event == "MERCHANT_SHOW" then
        SellAndRepair()
    end
  end)
--[[
    elseif event == "QUEST_GREETING" then
		QuestGreeting()
	elseif event == "QUEST_DETAIL" then
		QuestDetail()
    elseif event == "QUEST_ACCEPT_CONFIRM" then
		QuestAcceptConfirm()
	elseif event == "QUEST_ACCEPTED" then
		QuestAccepted()
	elseif event == "QUEST_PROGRESS" then
		QuestProgress()
	elseif event == "QUEST_ITEM_UPDATE" then
		QuestItemUpdate()
	elseif event == "QUEST_COMPLETE" then
		QuestComplete()
	elseif event == "QUEST_FINISHED" then
		QuestFinished()
	elseif event == "QUEST_AUTOCOMPLETE" then
		ShowQuestComplete()
	end
end)

function testMe()
  QuestGrid11.texture:SetColorTexture(colorNine[1], colorNine[2], colorNine[3])
end

]]
